### ISSUE TITLE
Problems with the cover block example

### ISSUE THREAD

**Issue by themetips** [Automattic/gutenberg-block-styles#2]
The example with the cover block does not work,
It causes the error `TypeError: Cannot read property 'innerBlocks' of null`
and the example should be removed.

Related: https://github.com/WordPress/gutenberg/issues/9897

**Comment by kjellr** [comment]
Thanks for the report! 

Looks like that issue [was fixed yesterday](https://github.com/WordPress/gutenberg/pull/15561), and will land in Gutenberg 5.8. I've tested the cover image example there and it works, so I'll leave the example active for now. 👍
