### ISSUE TITLE
Style doesn't add class

### ISSUE THREAD

**Issue by Denis74F** [Automattic/gutenberg-block-styles#4]
Hi @kjellr , I'm trying to set different styles for some blocks I created. I've tried to follow all the guides but can't get it to work.
If I apply different styles to a WordPress core block it works perfectly. If I try to apply it to a block created by me it doesn't work.
This is my js code:

```
const { registerBlockType } = wp.blocks;
const { __ } = wp.i18n
const { useState } = wp.element
const { RichText, InspectorControls} = wp.blockEditor;
const { ToggleControl, PanelBody, PanelRow, CheckboxControl, SelectControl, ColorPicker,RangeControl,Button,ButtonGroup,Guide,FontSizePicker,TextControl} = wp.components;


registerBlockType('df/carouselblock', {
	title: __('DF Carousel','df-carousel'),
	category: 'df-block',
	icon: {foreground: '#82b541',src:'embed-photo'},
	description: __('Learning in progress','df-carousel'),
    keywords: [__('example','df-carousel'), __('test','df-carousel')],
    // Register block styles.
    styles: [
    // Mark style as default.
        {
        name: 'default',
        label: __( 'Rounded' ),
        isDefault: true
        },
        {
        name: 'outline',
        label: __( 'Outline' )
        },
        {
        name: 'squared',
        label: __( 'Squared' )
        },
    ],
	
    supports: {
		// Add alignwide and alignfull options
		align: true,
		align: ['center', 'wide', 'full'],
        },
	attributes: {
        df_title_write:{
            type:'string',
            default:__('DF WRITE','df-carousel'),
        },
    
	},
	edit: (props) => { 
      
        const { attributes, setAttributes } = props;
       
       
    
		return (
           <div>Hello</div>
		);
    },
	save: props => {return null},
	//Example function 
	example: () => {}, // Get block preview 

});


```
Any help would be appreciated, thanks.

**Comment by kjellr** [comment]
👋 Hey @Denis74F! I don't see any issues with the block styles portion of your code there (aside from a missing textdomain for the label translation, but that wouldn't cause any issues). 

Are your custom block styles selectable in the editor at all?

**Comment by Denis74F** [comment]
Hi, yes the styles are selectable. The weird thing I noticed is that the block doesn't take the block name class "df-carouselblock", as per attached screenshot.

![Schermata 2020-12-15 alle 16 27 56](https://user-images.githubusercontent.com/60289158/102236042-4e813e00-3ef3-11eb-8efc-183eef528a4b.png)

Even if you select styles, classes are not added anywhere.

**Comment by kjellr** [comment]
I'm not an expert in building custom blocks, but I think the issue could be that you're not adding a `className` prop to the output. 

If you check out the example here, you'll see that there's a `className` property added to the `props`, which is added to the element via `className={ props.className }`.

**Comment by Denis74F** [comment]
Hi @kjellr , I solved it thanks to your advice. I added the class and now it works perfectly, that's where the problem was. I thought it was added with style names, but without this call they are not added. I am attaching the correct code, it might be useful as well if anyone encounters this problem.

```
const { registerBlockType } = wp.blocks;
const { __ } = wp.i18n
const { useState } = wp.element
const { RichText, InspectorControls} = wp.blockEditor;
const { ToggleControl, PanelBody, PanelRow, CheckboxControl, SelectControl, ColorPicker,RangeControl,Button,ButtonGroup,Guide,FontSizePicker,TextControl} = wp.components;


registerBlockType('df/carouselblock', {
	title: __('DF Carousel','df-carousel'),
	category: 'df-block',
	icon: {foreground: '#82b541',src:'embed-photo'},
	description: __('Learning in progress','df-carousel'),
    keywords: [__('example','df-carousel'), __('test','df-carousel')],
    // Register block styles.
    styles: [
    // Mark style as default.
        {
        name: 'default',
        label: __( 'Rounded','df-carousel' ),
        isDefault: true
        },
        {
        name: 'outline',
        label: __( 'Outline','df-carousel' )
        },
        {
        name: 'squared',
        label: __( 'Squared','df-carousel' )
        },
    ],
	


	edit: (props) => { 

      
        const { attributes, setAttributes } = props;
       
        
    
		return (
           <div className={ props.className }>  {__('Hello','df-carousel')}</div>
		);
    },
	save: props => {return null},
	

});

```

Thanks again.

Regards

Denis

**Comment by kjellr** [comment]
Awesome! Glad it's all sorted out.
